version: "2"
services:
  db:
    image: postgres:12.3
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db_setup/setup.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - backend
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run migrate:up && npm start
    volumes:
      - .:/src/app
      - node_modules_volume:/src/app/node_modules/
    links:
      - db
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - backend
    environment:
      DATABASE_URL: postgres://postgres@db:5433/finance
      JWT_SECRET: ISSA_SECRET
volumes:
  node_modules_volume:
  data:
    driver: local
networks:
  backend:
